sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc
  - npm install
script:
  - npm test
beforescript:
  - testrpc > /dev/null & 
afterscript:
  - npm run coverage
  - codecov